{{- if and (not .Values.argocd.webhookPasswordSecretName) .Values.argocd.webhookPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "git-monitor.webhookSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "git-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.argocd.webhookPassword | quote }}
{{- end }}
